stages:
  - tag
  - build

variables:
  AWS_ROLE_US0: aws:v1/o11y-infra/role/gitlab_signalflow_library_versions_management-us0

build and deploy:
  stage: build
  only:
    refs:
      - master
  before_script:   
    - creds-helper init
    - creds-helper aws --eval ${AWS_ROLE_US0}
    - mkdir ~/.aws
    - ls /root/.secrets/
    - mv /root/.secrets/awsv1o11y-infrarolegitlab_signalflow_library_versi.aws ~/.aws/credentials
  script:
    - VERSION="$(gitversion show)"
    - ./mkrelease $VERSION
    - ls -la
    - aws s3 cp signalfx-$VERSION.zip s3://signalflow-library-versions-us0-signalfx/
    - aws s3 ls s3://signalflow-library-versions-us0-signalfx/

tag-release:
  stage: tag
  only:
    refs:
      - master
  before_script:
    - eval $(ssh-agent -s)
    - go-go git-ssh
    - git config --global user.email "${CI_PROJECT_NAME}@splunk.com"
    - git config --global user.name "CI Auto User"
  script:
    - echo "Latest version $(gitversion show)"
    - BUMPED_VERSION="$(gitversion bump auto)"
    - echo "New version ${BUMPED_VERSION}"
    - git tag -f "${BUMPED_VERSION}"
    - git push origin-ssh "${BUMPED_VERSION}" -o ci.skip

