stages:
  - tag
  - build
  - deploy
  - lab0-release
  - test-lab0
  - dev-release
  - test-rc0
  - promote
  - prod-release

variables:
  AWS_ROLE: aws:v1/o11y-infra/role/gitlab_private_signalflow_library_versions_management
  GCP_ROLE: gcp:v1/o11y-infra/project/lab1-env-716/roleset/o11y-signalflow-bucket-access-lab1

tag-release:
  stage: tag
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - eval $(ssh-agent -s)
    - go-go git-ssh
    - git config --global user.email "${CI_PROJECT_NAME}@splunk.com"
    - git config --global user.name "CI Auto User"
  script:
    - echo "Latest version $(gitversion show)"
    - BUMPED_VERSION="$(gitversion bump auto)"
    - echo "New version ${BUMPED_VERSION}"
    - git tag -f "${BUMPED_VERSION}"
    - git push origin-ssh "${BUMPED_VERSION}" -o ci.skip

build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  allow_failure: false
  script:
    - VERSION="$(gitversion show)"
    - echo VERSION=${VERSION} >> build.env
    - ./mkrelease "${VERSION}"
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - "signalfx-*.zip"

deploy-aws:
  image: docker.repo.splunkdev.net/ci-cd/ci-container/debian-buster-aws:1.0.0
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  allow_failure: false
  before_script:
    - creds-helper init
    - creds-helper aws --eval ${AWS_ROLE}
    - mkdir ~/.aws
    - mv /root/.secrets/awsv1o11y-infrarolegitlab_private_signalflow_libra.aws ~/.aws/credentials
  script:
    - aws s3 cp "signalfx-${VERSION}.zip" s3://private-signalflow-library-versions-signalfx/

deploy-gcp:
  image: docker.repo.splunkdev.net/ci-cd/ci-container/debian-buster-gcloud:1.0.0
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  allow_failure: false
  before_script:
    - creds-helper init
    - eval $(creds-helper gcp --eval ${GCP_ROLE})
    - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
  script:
    - gsutil cp "signalfx-${VERSION}.zip" gs://private-signalflow-library-versions-signalfx

promote-private-to-public:
  image: docker.repo.splunkdev.net/ci-cd/ci-container/debian-buster-aws:1.0.0
  stage: promote
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - creds-helper init
    - creds-helper aws --eval ${AWS_ROLE}
    - mkdir ~/.aws
    - mv /root/.secrets/awsv1o11y-infrarolegitlab_private_signalflow_libra.aws ~/.aws/credentials
  script:
    - aws s3 cp "s3://private-signalflow-library-versions-signalfx/signalfx-${VERSION}.zip" s3://public-signalflow-library-versions-signalfx/

.release:
  variables:
    JENKINS_JOB: signalflow-library-deploy-$REALM
    JENKINS_PARAMS: VERSION=$VERSION
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  allow_failure: false
  trigger:
    project: observability/shared/jenkins-jumpbox
    branch: main
    strategy: depend

.dev-release:
  extends: .release
  stage: dev-release

.prod-release:
  extends: .release
  stage: prod-release
  when: manual
  variables:
    JENKINS_URL: "https://ci-deploy.signalfx.com"

lab0-release:
  extends: .dev-release
  stage: lab0-release
  variables:
    REALM: lab0
    JENKINS_URL: "https://ci-master.corp.signalfx.com"

lab1-release:
  extends: .dev-release
  variables:
    REALM: lab1
    JENKINS_URL: "https://ci-deploy-dev.signalfx.com"

lab2-release:
  extends: .dev-release
  allow_failure: true
  variables:
    REALM: lab2
    JENKINS_URL: "https://ci-deploy-dev.signalfx.com"

rc0-release:
  extends: .dev-release
  when: manual
  variables:
    REALM: rc0
    JENKINS_URL: "https://ci.corp.signalfx.com"

us0-release:
  extends: .prod-release
  variables:
    REALM: us0

us1-release:
  extends: .prod-release
  variables:
    REALM: us1

us2-release:
  extends: .prod-release
  variables:
    REALM: us2

eu0-release:
  extends: .prod-release
  variables:
    REALM: eu0

pypl-us0-release:
  extends: .prod-release
  variables:
    REALM: pypl-us0

pypl-us1-release:
  extends: .prod-release
  variables:
    REALM: pypl-us1

jp0-release:
  extends: .prod-release
  variables:
    REALM: jp0

au0-release:
  extends: .prod-release
  variables:
    REALM: au0

mon0-release:
  extends: .prod-release
  variables:
    REALM: mon0

.test:
  variables:
    JENKINS_URL: "https://ci-qe.corp.signalfx.com/"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  allow_failure: true
  trigger:
    project: observability/shared/jenkins-jumpbox
    branch: main
    strategy: depend

test-lab0:
  extends: .test
  stage: test-lab0
  variables:
    JENKINS_JOB: lab-system-test-signalflow-library

test-rc0:
  extends: .test
  stage: test-rc0
  variables:
    JENKINS_JOB: rc-system-test-signalflow-library